// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ScoreboardPatch } from "./ScoreboardPatch";

/**
 * One enum drives local commands, hotkeys and WS commands. Adding a feature
 * means adding a variant, and the compiler finds every place that must
 * handle it.
 */
export type Action =
	| { action: "patch"; data: ScoreboardPatch }
	| { action: "score-home-inc" }
	| { action: "score-home-dec" }
	| { action: "score-away-inc" }
	| { action: "score-away-dec" }
	| { action: "half-inc" }
	| { action: "half-dec" }
	| { action: "timer-start" }
	| { action: "timer-pause" }
	| { action: "timer-stop" }
	| { action: "timer-set"; data: { seconds: number } }
	| { action: "timer-adjust"; data: { delta: number } }
	| { action: "timer-loadout"; data: { slot: number } }
	| { action: "buzzer-play" }
	| { action: "reset" };
