// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Pipeline step (doc 06 §B5).
 */
export type GenerationStep = "idle" | "parsing" | "rendering" | "encoding" | "cleanup" | "complete" | "error";
