// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { GenerationStep } from "./GenerationStep";

/**
 * Progress model (doc 06 §B5) emitted as `video:progress`.
 */
export type GenerationProgress = {
	step: GenerationStep;
	/**
	 * 0..100 within the current step.
	 */
	stepProgress: number;
	/**
	 * 0..100 overall (bands: parsing 0–5, rendering 10–60, encoding 60–95,
	 * cleanup 95, complete 100 [PARITY]).
	 */
	overallProgress: number;
	currentFrame: number | null;
	totalFrames: number | null;
	message: string;
	error: string | null;
};
