// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Returned by `video_generate`: frame count and output dimensions the
 * webview needs to size its canvas and drive the render loop.
 */
export type GenerationStarted = { totalFrames: number; width: number; height: number };
