// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A window hotkey: a `KeyboardEvent.key` value plus modifiers.
 */
export type HotkeyBinding = {
	/**
	 * `KeyboardEvent.key`; single characters are stored lowercase.
	 */
	key: string;
	ctrl: boolean;
	shift: boolean;
	alt: boolean;
};
