// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type LanAddress = {
	/**
	 * Interface name, e.g. `eth0` / `Wi-Fi`.
	 */
	name: string;
	/**
	 * Dotted-quad IPv4 address.
	 */
	address: string;
};
