// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Partial update over [`MatchPreset`]; `None` leaves the field unchanged.
 */
export type MatchPresetPatch = {
	/**
	 * Nullable vs absent: `None` = leave, `Some(None)` = clear the label.
	 * From JSON, send `""` to clear — a nested `Option` cannot distinguish
	 * `null` from absent.
	 */
	label?: string | null;
	homeTeamId?: string;
	awayTeamId?: string;
};
