// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A fixture: two team references. Carries no match values.
 */
export type MatchPreset = {
	id: string;
	/**
	 * Optional user label. When absent the UI and the menu show
	 * `"{home} vs {away}"`, so the common case needs no typing.
	 */
	label?: string | null;
	homeTeamId: string;
	awayTeamId: string;
};
