// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { MatchPreset } from "./MatchPreset";
import type { TeamPreset } from "./TeamPreset";

/**
 * The whole preset library, read by the frontend in a single round trip.
 */
export type PresetLibrary = { schemaVersion: number; teams: Array<TeamPreset>; matches: Array<MatchPreset> };
