// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One entry of the recent-recordings list in the recording window
 * (doc 06 §A6).
 */
export type RecentRecording = {
	fileName: string;
	filePath: string;
	sizeBytes: number;
	modifiedUnixSecs: number;
};
