// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Snapshot } from "./Snapshot";

/**
 * Parsed recording header + first snapshots, for the generator window's
 * Recording File card (doc 06 §B7).
 */
export type RecordingMetadata = {
	recordingId: string;
	startedAt: string;
	endedAt: string | null;
	homeName: string;
	awayName: string;
	snapshotCount: number;
	durationSecs: number;
	firstSnapshots: Array<Snapshot>;
};
