// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Live recording status. Emitted as `recording:status` on
 * start, stop and every snapshot.
 */
export type RecordingStatus = {
	isRecording: boolean;
	recordingId: string | null;
	filePath: string | null;
	snapshotCount: number;
	durationSecs: number;
};
