// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Result of `recording_stop`.
 */
export type RecordingStopped = { filePath: string; totalSnapshots: number };
