// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { TimerDirection } from "./TimerDirection";

export type ScoreboardState = {
	teamHomeName: string;
	teamAwayName: string;
	teamHomeScore: number;
	teamAwayScore: number;
	teamHomeColor: string;
	teamAwayColor: string;
	/**
	 * Seconds shown on the board: remaining when counting down, elapsed
	 * when counting up.
	 */
	timer: number;
	half: number;
	halfPrefix: string;
	/**
	 * Reserved; unimplemented.
	 */
	eventLogo: string | null;
	/**
	 * Read-only for clients; only the timer engine sets it.
	 */
	isTimerRunning: boolean;
	/**
	 * Read-only for clients; mutated only via [`Action::TimerSetDirection`]
	 * (which pauses first) so the running engine can never desync.
	 */
	timerDirection: TimerDirection;
	timerLoadout1: number;
	timerLoadout2: number;
	timerLoadout3: number;
	/**
	 * Monotonic, bumped on every mutation. Never exposed in the UI.
	 */
	revision: number;
};
