// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Partial update. Every field except `is_timer_running` and `revision`.
 *
 * `deny_unknown_fields` is deliberate: the Electron server silently swallowed
 * typos in `POST /api/scoreboard`. Return 400 with the offending field.
 */
export type ScoreboardPatch = {
	teamHomeName?: string;
	teamAwayName?: string;
	teamHomeScore?: number;
	teamAwayScore?: number;
	teamHomeColor?: string;
	teamAwayColor?: string;
	/**
	 * Routed to `Action::TimerSet`, never written directly — otherwise a
	 * patch would silently desync the running engine.
	 */
	timer?: number;
	half?: number;
	halfPrefix?: string;
	eventLogo?: string;
	timerLoadout1?: number;
	timerLoadout2?: number;
	timerLoadout3?: number;
};
