// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ScoreboardState = {
	teamHomeName: string;
	teamAwayName: string;
	teamHomeScore: number;
	teamAwayScore: number;
	teamHomeColor: string;
	teamAwayColor: string;
	/**
	 * Seconds remaining on the countdown.
	 */
	timer: number;
	half: number;
	halfPrefix: string;
	/**
	 * Reserved; unimplemented (see doc 08 open question 3).
	 */
	eventLogo: string | null;
	/**
	 * Read-only for clients; only the timer engine sets it.
	 */
	isTimerRunning: boolean;
	timerLoadout1: number;
	timerLoadout2: number;
	timerLoadout3: number;
	/**
	 * Monotonic, bumped on every mutation. Never exposed in the UI.
	 */
	revision: number;
};
