// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Lightweight, frequently-changing server counters for the status bar
 * (doc 02 §7.1.1). Emitted as `server:status`, coalesced to 2 Hz.
 */
export type ServerStatus = {
	running: boolean;
	port: number;
	/**
	 * Currently connected WebSocket clients.
	 */
	wsClients: number;
	/**
	 * Connected WebSocket clients currently permitted to send commands.
	 */
	authorizedClients: number;
	/**
	 * [OPTIONAL] Overlay mode (Phase 7).
	 */
	overlayActive: boolean;
	/**
	 * [OPTIONAL] Match recording (Phase 8).
	 */
	recordingActive: boolean;
	/**
	 * [OPTIONAL] Elapsed recording seconds (Phase 8).
	 */
	recordingSeconds: number;
};
