// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { LanAddress } from "./LanAddress";

/**
 * Heavy server description for the Outputs window (doc 02 §7.1): carries
 * the LAN URLs and changes rarely. Emitted as `server:info`.
 */
export type ServerInfo = {
	running: boolean;
	port: number;
	addresses: Array<LanAddress>;
	/**
	 * `http://<lan-ip>:<port>/scoreboard` for the first LAN address.
	 */
	scoreboardUrl: string;
	/**
	 * `http://localhost:<port>/scoreboard`.
	 */
	localUrl: string;
	/**
	 * Token-bearing LAN URL used by the remote-control QR code.
	 */
	controlUrl: string;
	/**
	 * Inline SVG encoding [`Self::control_url`].
	 */
	controlQrSvg: string;
	/**
	 * Always true until the Phase 5 settings toggle lands.
	 */
	tokenRequired: boolean;
};
