// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Lightweight, frequently-changing server counters for the status bar.
 * Emitted as `server:status`, coalesced to 2 Hz.
 */
export type ServerStatus = {
	running: boolean;
	port: number;
	/**
	 * Currently connected **external** WebSocket clients (OBS sources,
	 * phones, remote dashboards). In-app connections — the Outputs window's
	 * scoreboard-preview iframe — are excluded so the gauge reflects real
	 * LAN viewers, not app plumbing.
	 */
	wsClients: number;
	/**
	 * Connected WebSocket clients currently permitted to send commands.
	 */
	authorizedClients: number;
	/**
	 * [OPTIONAL] Overlay mode; always false, the overlay is not implemented.
	 */
	overlayActive: boolean;
	/**
	 * [OPTIONAL] Match recording.
	 */
	recordingActive: boolean;
	/**
	 * [OPTIONAL] Elapsed recording seconds.
	 */
	recordingSeconds: number;
};
