// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type Settings = {
	schemaVersion: number;
	serverPort: number;
	requireControlToken: boolean;
	/**
	 * [NEW] Optionally pin the control token so a bookmarked phone link
	 * survives restarts. `None` (default) regenerates every launch.
	 */
	pinnedControlToken: string | null;
	/**
	 * Custom buzzer track selected by the user; `None` = built-in default.
	 */
	buzzerTrackPath: string | null;
	buzzerAutoPlay: boolean;
	halfPrefix: string;
	teamHomeName: string;
	teamAwayName: string;
	teamHomeColor: string;
	teamAwayColor: string;
	timerLoadouts: [number, number, number];
};
