// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Partial update over [`Settings`]; `None` leaves the field unchanged.
 *
 * `deny_unknown_fields` matches the `ScoreboardPatch` discipline: a typo in
 * the Settings window surfaces as an error instead of being dropped.
 */
export type SettingsPatch = {
	serverPort?: number;
	requireControlToken?: boolean;
	/**
	 * Nullable vs absent: `None` = leave, `Some(None)` = clear, `Some(Some(p))` = set.
	 */
	buzzerTrackPath?: string | null;
	buzzerAutoPlay?: boolean;
	halfPrefix?: string;
	teamHomeName?: string;
	teamAwayName?: string;
	teamHomeColor?: string;
	teamAwayColor?: string;
	timerLoadouts?: [number, number, number];
};
