// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One per-second capture of the match state (doc 06 §A2.1). Field names are
 * deliberately short — the line repeats ~5 400 times in a 90-minute match.
 * Names/colours/prefix repeat on every line so each line is independently
 * renderable. TS-exported for the video generator's render loop (Phase 9).
 */
export type Snapshot = {
	/**
	 * Relative seconds since start, starting at 0.
	 */
	t: number;
	/**
	 * Home score.
	 */
	hs: number;
	/**
	 * Away score (`as` is a Rust keyword).
	 */
	as: number;
	/**
	 * Timer seconds remaining.
	 */
	tm: number;
	/**
	 * Half.
	 */
	hf: number;
	/**
	 * Home / away names.
	 */
	hn: string;
	an: string;
	/**
	 * Home / away colours.
	 */
	hc: string;
	ac: string;
	/**
	 * Half prefix.
	 */
	hp: string;
};
