// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A reusable team identity. Referenced by [`MatchPreset`], never inlined,
 * so renaming a team updates every fixture that uses it.
 */
export type TeamPreset = {
	/**
	 * 12 lowercase hex characters; see [`PresetId`].
	 */
	id: string;
	name: string;
	color: string;
};
