// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Partial update over [`TeamPreset`]; `None` leaves the field unchanged.
 */
export type TeamPresetPatch = { name?: string; color?: string };
