// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Whether the timer counts down to zero (buzzer at 0) or up from zero
 * (frozen at the [`MAX_TIMER_SECS`] cap, no buzzer).
 */
export type TimerDirection = "down" | "up";
