// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Generation configuration (doc 06 §B2).
 */
export type VideoGenerationConfig = {
	recordingPath: string;
	/**
	 * Must end in `.webm` (doc 06 §B2).
	 */
	outputPath: string;
	/**
	 * 1..=60, default 30.
	 */
	frameRate: number;
	/**
	 * 0.5..=3.0, default 1.0.
	 */
	scoreboardScale: number;
};
